#!/bin/bash

cd /var/www/vhosts/fraeulein-maya.de/frln.tools/ 
/var/www/vhosts/fraeulein-maya.de/usr/bin/php wp rocket clean --confirm --path=/var/www/vhosts/fraeulein-maya.de/httpdocs
/var/www/vhosts/fraeulein-maya.de/usr/bin/php wp rocket preload --path=/var/www/vhosts/fraeulein-maya.de/httpdocs
