#!/bin/bash

## COLORS
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

cd ~/html

COUPON_NAME=""

if [ -z $1 ]; then
    echo "❌ ${RED}no coupon name set ${RESET}"
    exit 1
else
    COUPON_NAME=$1
    echo "✅ ${GREEN} coupon name set to: ${RESET} \"${COUPON_NAME}\""
    echo "🔎  looking, if coupon code already exists"
    DOES_COUPON_CODE_EXIST=$(wp wc shop_coupon list  --user=demaya --fields=id,code,usage_count,description --format=table | grep ${COUPON_NAME} | wc -l)
    if [ ${DOES_COUPON_CODE_EXIST} -gt 0 ]; then
       echo "❌ ${RED}coupon already exists ${RESET}" 
    else 
	
    fi
fi

##
#wp wc shop_coupon create --code=test123 --amount='10' --discount_type='percent' --individual_use=true --excluded_product_ids="[19341]" --usage_limit_per_user='1' --description='Influencer-Code' --user='demaya'
